# Generated by Django 4.2 on 2025-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('message', models.TextField(max_length=256)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
